<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="PasswordGeneratorService"
     targetNamespace="http://passwordgeneratorservice/"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://passwordgeneratorservice/"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="PasswordGeneratorService">
        <plnk:role name="PasswordGenerator" portType="tns:PasswordGenerator"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://passwordgeneratorservice/" location="http://soabpm-vm.site:7001/PasswordGenerator-PasswordGeneratorService-context-root/PasswordGeneratorSoap12HttpPort?wsdl"/>
</wsdl:definitions>
