<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="FreightRequestParserService"
     targetNamespace="http://twitterparsefreightrequest/"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://twitterparsefreightrequest/"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="ParseRequest">
        <plnk:role name="FreightRequestParser" portType="tns:FreightRequestParser"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://twitterparsefreightrequest/" location="http://soabpm-vm.site:7001/TwitterParseFreightRequest-Project1-context-root/FreightRequestParserSoap12HttpPort?wsdl"/>
</wsdl:definitions>
