<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="properties"
     targetNamespace="http://xmlns.oracle.com/SendInvoice/TwitterFreightRequest/ProcessTwitterClientRequest/correlationset"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
    >
    <vprop:property name="SenderId" type="xsd:long"/>
    <vprop:property name="ConversationId" type="xsd:long"/>
</wsdl:definitions>
