<?binding.jca DeleteTransporter_db.jca?>
<wsdl:definitions name="DeleteTransporter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/RemoveTransporter/RemoveTransporterService/DeleteTransporter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DeleteTransporter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/RemoveTransporter/RemoveTransporterService/DeleteTransporter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="DeleteTransporter_plt">
        <plt:role name="DeleteTransporter_role">
            <plt:portType name="tns:DeleteTransporter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DeleteTransporter" schemaLocation="xsd/DeleteTransporter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="DeleteTransporterInput_msg">
        <wsdl:part name="DeleteTransporterInput_msg" element="db:DeleteTransporterInput"/>
    </wsdl:message>
    <wsdl:portType name="DeleteTransporter_ptt">
        <wsdl:operation name="DeleteTransporter">
            <wsdl:input message="tns:DeleteTransporterInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
